// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDSsUPF7B_gqZKg7KicGxmWfeN99_8yZKg',
    appId: '1:608973593261:web:ba58c84d3ebf1332e38424',
    messagingSenderId: '608973593261',
    projectId: 'flutter-note-app-3a75b',
    authDomain: 'flutter-note-app-3a75b.firebaseapp.com',
    storageBucket: 'flutter-note-app-3a75b.appspot.com',
    measurementId: 'G-3J5GPYY15H',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAQZvJZy9VaszlxtfhOWlZk7Z1MYB4KLJA',
    appId: '1:608973593261:android:df589bc9e2ebf9ebe38424',
    messagingSenderId: '608973593261',
    projectId: 'flutter-note-app-3a75b',
    storageBucket: 'flutter-note-app-3a75b.appspot.com',
  );
}
